### ISSUE TITLE
`febio_spec.Control.analysis.ATTR.type='static'` error in `DEMO_febio_0067_hip_implant_regional_stiffness_optimize_01.m`

### ISSUE THREAD

**Issue by modenaxe** [gibbonCode/GIBBON#134]
Hello, 
I was exploring the demos and I was particularly interested in `DEMO_febio_0067_hip_implant_regional_stiffness_optimize_01.m`.
The script, however has an issue at line 696, where it tries to import a file that does not exist (`'SED_no_implant.mat`).
The file name is defined in line 37:
```
loadName_SED=fullfile(savePath,'SED_no_implant.mat');
```
but I do not understand if 'SED_no_implant.mat' is missing (it is not included in the current version of the repository) or it should be generated by the script at some point. With a little direction I am happy to try and fix it.
Thank you,
Luca

**Comment by gooyle** [comment]
I run the sctipt `DEMO_febio_0067_hip_implant_regional_stiffness_optimize_01.m`, another error happens : ` error : DEMO_febio_0067_hip_implant_regional_stiffness_optimize_01 (873 line)  febio_spec.Control.analysis.ATTR.type='static';`
Perhaps you could try to run the demo `testGibbon` to run all the demo

**Comment by modenaxe** [comment]
I have reinstalled GIBBON and FEBio and I actually have your same error @gooyle !

**Comment by NataCalc** [comment]
Hi @modenaxe,

Run first DEMO_febio_0062_femur_load_01.m (femur under static physiological loading). In this code you save strain energy density without implant in the "SED_no_implant.mat". Then, run DEMO_febio_0067_hip_implant_regional_stiffness_optimize_01. In this code you will load SED data from non-implant model. 
I hope it will help. 

Hi @gooyle ,
You have the problem because uncompatibility. The code DEMO_febio_0067_hip_implant_regional_stiffness_optimize_01 is written for the FEBio 2.5 version where, I believe, on your computer the FEBio3 is installed and GIBBON is calling FEBio3 via the path. I upgraded the code up to FEBio3. Please, download only this code and give a try running it. Let me know if it works for you.

**Comment by modenaxe** [comment]
thank you @NataCalc, I didn't understand that the examples were to run sequentially, now it works!

**Comment by NataCalc** [comment]
You are welcome @modenaxe. If you have further questions do not hesitate to ask.

**Comment by Kevin-Mattheus-Moerman** [comment]
Thanks for your help @NataCalc! @modenaxe thanks for posting this, let me know if you need any more help. I'll close this for now but let me know if you'd like me to reopen it for any reason. Also I hope you'll consider contributing useful changes you make back to the GIBBON project.
