### ISSUE TITLE
Smoothing a Quad Mesh

### ISSUE THREAD

**Issue by LawSmith408** [gibbonCode/GIBBON#138]
I am looking to obtain a smooth hexahedral mesh of a thin gyroid triply periodic minimal surface.  The end result I'm looking for is something like this (except using hex elements instead of tets. This image generated using the triplyPeriodicMinimal and runTetGen documentation)

![image](https://user-images.githubusercontent.com/32077819/174489920-941cc5ca-a139-495e-8e7c-fcd014bbba42.png)

I use tri2quad to subdivide triangular faces of a zero-thickness gyroid isosurface into quads. 

![image](https://user-images.githubusercontent.com/32077819/174490035-e1f9b3bc-bb7d-41b0-979d-314cc55d0a73.png)

It appears that the algorithm used follows the first half of the algorithm presented in this paper:

https://acdl.mit.edu/ESP/Publications/IMR28.pdf

I'd like to smooth the resulting quad mesh, but I am having trouble... in part because I'm not sure whether to use quad_smooth, tesSmooth, or patchSmooth.

I created a demo script to play around with quad_smooth, but I'm not able to parse exactly how the inputs are used. Could you shed a little light for me? Here's my demo code!

[F,V]=stanford_bunny;
[Fq,Vq]=tri2quad(F,V,2);

Ev = 2:size(Vq,1); % Is this a list of the indices of nodes we will adjust
IND_V_not_Ev = 1; %this might be the complement of 
Lc = Ev';  %not sure what this is
n = 20; %number of algorithm iterations
Ls = 0.75; %this seems like a scaling parameter for adjusting positions
w1 = 0.9;  %not sure what this weight is

% V2=quad_smooth(Vq,Ev,IND_V_not_Ev,Lc,n,Ls,w1);

cPar.Method='HC';
cPar.n=15;
cPar.RigidConstraints=[];
% [V2]=tesSmooth(Fq,Vq,[],cPar);

[V2]=patchSmooth(Fq,Vq,[],cPar);

if ~norm(Vq-V2)
    disp('Input and Output Meshes Identical')
end

subplot(1,2,1); gpatch(Fq,Vq); view(3); axis equal; hold on
subplot(1,2,2); gpatch(Fq,V2); view(3); axis equal
set(gcf,'Position',[302 248 1224 733])

**Comment by LawSmith408** [comment]
I will also add that it appears like this is a nontrivial problem... not a lot of other options for generating smooth quad meshes on arbitrary geometries. 

Here is the best result I could get using Blender:
![image](https://user-images.githubusercontent.com/32077819/174490222-964578d2-1439-4f5a-97d2-fddad0170fd8.png)

Which is quad-dominated but still contains some tris.

This is what I get using InstantMeshes, a free tool based on a SIGGRAPH paper:
https://github.com/wjakob/instant-meshes

Which appears to do a slightly better job, but still includes some tris and also some pentagons (which would eventually require transition elements for finite element analysis)
![image](https://user-images.githubusercontent.com/32077819/174490625-5ed84d5e-eb86-4ed2-93f1-cf903fe06022.png)


The is another commercial option which claims to outperform InstantMeshes:
https://geometryfactory.com/products/igm-quad-meshing/

**Comment by Kevin-Mattheus-Moerman** [comment]
Hi @LawSmith408, thanks for using GIBBON and for posting this issue. Apologies for the slow response. 

Why is it that you need quad or hex elements? Could you use tetrahedral elements or pentahedral elements (thickened triangles). 

You may be interested in this way to create quad meshes from triangulations: 
https://www.gibboncode.org/html/HELP_tri2quadGroupSplit.html
Note, this approach does split the elements once if you want a full quad mesh. Also this code is slow since it looks over elements. 

Isosurfaces provide horrible triangulations, here is a code which can resample it in an improved way (although it does smooth the surface a little too), or perhaps you have used this already?: 
https://www.gibboncode.org/html/HELP_ggremesh.html
You could consider doing ggremesh first prior to element conversion. 

The best approach to get a quisi-regular quad mesh, which I have not implemented yet, is something like what is done here:, 
https://onlinelibrary.wiley.com/doi/full/10.1002/adfm.202101373
I.e. to create a quad mesh in the hyperbolic space and project to Euclidian space. I am talking to that author to implement it. He is also part of the GIBBON community. @SebastienCallens :wave: 

On smoothing, I think you might not need that. I think when you say smooth, you might actually mean "regular" or quasi-regular quads, e.g. that the quad mesh looks rather ordered (not a mess). Smoothing for meshes is different, it makes rough and noisy shapes more smooth. It can make the mesh more regular looking too but I would say the primary action is also to alter the shape, which is probably not what  you want. On smoothing methods, yes my apologies I implemented it a couple of times. `quad_smooth` is old and should be deprecated. `tesSmooth` is intended also for volumetric meshes. The one to use for general surface meshes is `patchSmooth`. 

I hope these comments help. It would be fantastic if @SebastienCallens could help implement (in MATLAB) that better way to encode the triply periodic minimal surfaces. 

I hope this helps.

**Comment by LawSmith408** [comment]
Thank you for the great pointers - especially the Callens paper. It is a very interesting read!

I am interested in quad elements just out of curiosity - I would like to compare the finite element results for crushing TPMS structures as simulated by triangular shell, quadrilateral shell, and tetrahedral elements. I will check out the tri2quadGroupSplit function you mentioned!

You're right, I am aiming "regularization" and not "smoothing" - thanks for pointing that out.

I am well familiar with ggremesh and I currently use it to remesh triangulations extracted by calling isosurface().

**Comment by Kevin-Mattheus-Moerman** [comment]
@LawSmith408 how are you getting on? Let me know if you need more help.

**Comment by Kevin-Mattheus-Moerman** [comment]
@LawSmith408 I'll close this issue for now, but do let me know if you need any more help.
