### ISSUE TITLE
smoothCurve

### ISSUE THREAD

**Issue by jpv20** [gibbonCode/GIBBON#157]
hi Kevin...

i am running this example:
https://www.gibboncode.org/html/DEMO_febio_0060_vertebrae_disc_01.html

and i need the function smoothCurve....where can i find this function?

i am getting this error:  (And smoothCurve is not in the documentation for gibboncode online)....
Unrecognized function or variable 'smoothCurve'.

jonathan

**Comment by Kevin-Mattheus-Moerman** [comment]
@jpv20 that function is supplied at the end of that demo. Normally MATLAB finds all functions in a file (or at least since 2016 it seems: https://uk.mathworks.com/help/matlab/matlab_prog/local-functions-in-scripts.html). 

For Octave I noticed I have to move the function to the top of the file. Perhaps try that. Alternatively, copy the code and move it to a separate file known to MATLAB folder you are working in. I did not add this function to GIBBON as it is perhaps not the best way of doing it, so at the time it was a quick and not-quite-clean (not dirty though :) ) method. 

Hope this helps. 

```matlab
function [V1]=smoothCurve(F1,V1,nc,ns,indList1)
clear cPar
cPar.n=nc;
cPar.Method='HC';
e=[(1:numel(indList1))' [(2:numel(indList1))';1]];
v=V1(indList1,:);
[v]=patchSmooth(e,v,[],cPar);
V1(indList1,:)=v;

indTouch=unique(F1(any(ismember(F1,indList1),2),:));
indTouch=unique(F1(any(ismember(F1,indTouch),2),:));
logicRigid=true(size(V1,1),1);
logicRigid(indTouch)=0;
logicRigid(indList1)=1;
indRigid=find(logicRigid); 

cPar.n=ns;
cPar.Method='HC';
cPar.RigidConstraints=indRigid; 
[V1]=patchSmooth(F1,V1,[],cPar);
end
```

**Comment by Kevin-Mattheus-Moerman** [comment]
I'll close this one for now but let me know if you need more help and I'll re-open.
