### ISSUE TITLE
Installation: best way to chmod +x where necessary?

### ISSUE THREAD

**Issue by wspr** [gibbonCode/GIBBON#17]
I tried running the example file `/DEMO_MixedTetHexMeshing.m` and at one point it gracefully failed with:

```
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
--- Writing SMESH file --- 15-Jan-2018 14:03:11
----> Adding node field
----> Adding facet field
----> Adding holes specification
----> Adding region specification
--- Done --- 15-Jan-2018 14:03:11
--- Running TetGen to mesh input boundary--- 15-Jan-2018 14:03:11
/bin/bash: /Users/will/Repo/External/GIBBON/lib_ext/tetGen/mac64/tetgen: Permission denied
--- Done --- 15-Jan-2018 14:03:11
```

Now, that's an easy fix in my case:

    chmod +x /Users/will/Repo/External/GIBBON/lib_ext/tetGen/mac64/tetgen

But I wonder whether it would make sense to somehow automate this for all needed files. Are there best practices for doing this within Matlab itself? (I'm guessing the chmod settings aren't reliably preserved after a git clone but I could be wrong.)

**Comment by wspr** [comment]
Actually it looks like files in git should preserve their chmod-ness, and the following should work (famous last words) across platforms:

    git update-index --chmod=+x path/to/tetgen

**Comment by Kevin-Mattheus-Moerman** [comment]
@wspr thanks for your work on this.  What do you think is the best way to address this? I've had users where MATLAB and/or FEBio and/or TetGen presented with file permission issues (since all create and modify files and also GIBBON cleans these up by deleting temporary files). Am I correct in saying you only had file permission issues with TetGen itself? So the fix you present addresses that? Can you advise as to how I should address this issue, or say if my attempt described below is sufficient? 

I've now added a statement in the [README](https://github.com/gibbonCode/GIBBON/blob/master/README.md) to attempt to address potential file permission issues (see the first step in the installation process described): 

--- 
### 1. Get a copy of GIBBON
To use GIBBON you need to create a copy on a local directory on your machine. Obtain a copy by downloading and unzipping the latest [zip file](https://github.com/gibbonCode/GIBBON/archive/master.zip) or clone GIBBON instead e.g. using: `git clone https://github.com/gibbonCode/GIBBON.git`. You can place the GIBBON folder anywhere on your machine, however, MATLAB (and the 3rd party packages listed below) may have file permission limitations for some locations which you may need to address<sup>\*</sup>.   

<sup>\* For instance, some of GIBBON's features, such as those associated with TetGen and FEBio, regularly create and delete temporary files. As such MATLAB (and the 3rd party packes) should have full permissions for these folders. First of all users should make sure MATLAB has full (e.g. read/write/delete) permissions for the entire GIBBON folder (and its sub-folders). On some platforms the 3rd party packages require special treatment. For instance some OSX users have found it necessary to give tetGen or FEBio particular file permissions. For instance in the case of TetGen related features using `git update-index --chmod=+x path/to/tetgen`. </sup>

**Comment by wspr** [comment]
Thanks for the detailed reply, the text you've written looks good.

Sorry I was unclear above, though — my understanding (although it's hard for me to test this) is that if you write

    git update-index --chmod=+x path/to/your/tetgen

and push the resulting commit to Github it will then solve the problem for everyone. I tried looking (non-exhaustively, I want to emphasise!) to see if there were any other files that needed this done and came up blank, so I might have been just (un)lucky to stumble upon this early in testing.

If you give that a try I should be able to confirm.

**Comment by Kevin-Mattheus-Moerman** [comment]
@wspr I did `git update-index --chmod=+x path/to/something' for the mac and linux version of tetGen. The latest version should have this. Can you check it out?

**Comment by wspr** [comment]
@Kevin-Mattheus-Moerman — sorry for the slow feedback, I think it works!

**Comment by mid-2022** [comment]
git clone https://github.com/TEAM-FLAiN/FLAiN ;cd FLAiN;chmod +x install;./install install
