### ISSUE TITLE
Unit change in Gibbon simulation

### ISSUE THREAD

**Issue by ManDanSoE** [gibbonCode/GIBBON#175]
Hello,

I have been working with GIbbon for not too long so please keep that in mind. I have adjusted the code  DEMO_febio_0001_cube_uniaxial and changed the geometry to a cylinder instead. the only issue I am having is that the data is presented in MPa and I would like to change that to KPa. Is there any way to do this?

Thank you so much for your time

**Comment by Kevin-Mattheus-Moerman** [comment]
@ManDanSoE thanks for this post and question. Packages like FEBio are agnostic with respect of units. One could think of them as operating with the standard SI units i.e. Kg, m, s. This then means forces are in N, stresses are in Pa, and energy is in J, etc. In many of my demos I use mm instead m. There is nothing wrong with that, it just means the FEBio output should be interpreted differently. This table (from a different software package) on unit conversion is handy:
https://www.dynasupport.com/howtos/general/consistent-units

As you can see, when mm is used instead of m, one option is to interpret stresses in units of MPa and mass in ton. Of course there is only a factor of a 1000 different between MPa and KPa. By using a factor of 1000 you can just scale up/down units (e.g. if you want to use a material parameter that has units of kPa you simply enter it as 1/1000 = 1e-3 MPa in the code. And if you run a simulation and get output stresses of 1 MPa you can just multiply them by 1000 to get 1000 kPa). You can work out a similar system whereby everything is always in kPa. However, I would recommend either using m or mm and just to use scaling when you want stress to be represented (e.g. in summary statistics or visualisations for instance) differently.
