### ISSUE TITLE
anim8.m plays the vizualisation slower than the choosen speed.

### ISSUE THREAD

**Issue by Ipuch** [gibbonCode/GIBBON#36]
Hi,

I tried to use your useful anim8 tool to vizualise my musculoskeletal simulation of [CusToM](http://github.com/anmuller/CusToM). I used it on Matlab 2018a, on a Windows 10 with the following config: 
![image](https://user-images.githubusercontent.com/40755537/50307278-3effc380-0498-11e9-913a-918ded39c4bf.png)

However the function is not playing the simulation at real speed. Do you have any idea how to do it ?

One of my explanation is that the animStruct is too large to be handle by the anim8.m function.

![tuto2_muscleforce](https://user-images.githubusercontent.com/40755537/50306298-7caf1d00-0495-11e9-90af-63dd5dffabb7.gif)

Here it is the [link](https://drive.google.com/open?id=1Fun6rYu8dcLJAKLbupegUoLPz86y09vB) with a zip of the figure and the animStruct.
Best regards,

Pierre

**Comment by Kevin-Mattheus-Moerman** [comment]
Hi @Ipuch thanks for using GIBBON and for testing `anim8`. The short answer to your question is to speed things up by grouping things together into a single handle or a single one property. The long answer is below. 

You've probably found the timing setting icon on the top left right? Using this button you can set the pause time between frames: 
![screenshot from 2018-12-21 09-27-37](https://user-images.githubusercontent.com/8392709/50335306-c41fc280-0502-11e9-8548-7658024436c9.png)
Set the time step to 0 to see what your current maximum speed is. The maximum speed at which the animation can play is limited by the speed of  your computer and the amount of stuff MATLAB needs to for each time step. For each step it needs to loop over and update all the properties (i.e. set stuff like `'XData' , 'Color'`). It seems you have formulated the animation using: 
1. Many time steps (203)
2. Many properties and handles (610)

First of all skipping every second step would speed things up. However I can imagine one would not like to do that. Instead you could try to reduce the number of properties/handles you vary. Essentially it seems to be you are altering only 2 things, coordinates, and colors. If you can frame this using 2 handles you can achieve the maximum speed. So you should try to "group" things together. In the `HELP_anim8` example below I animate a bouncing bunny consisting of e.g. 12144 faces and 6074 vertices. I can however animate it rapidly because a single handle (the graphics handle to the bunny `patch` object) is used for only 3 properties `'FaceColor','Vertices','FaceAlpha'`. So I can change color, coordinates and transparency at a good speed. If I had tried to control the positions/properties of each face or vertex using a separate handle this would never have worked as efficiently due to the looping required. 

![figure4](https://user-images.githubusercontent.com/8392709/50335709-12819100-0504-11e9-8f01-7b612a6970bd.gif)

For this bunny I create the plot using: `hp=gpatch(F,V,'b')`. This type of graphics object (patch graphics) is very versatile and handy because you can changes `'Vertices'` in one go (so you do not need to set `'XData'`,  `'YData'`,  and `'ZData'`). Also it has `'CData'` allowing you to colormap the color of faces and/or edges. (see `HELP_gpatch`). Although usually `F` represents `faces`, you can also have it represent `edges`. E.g. you could define the entire wireframe skeleton using a nx2 array E (edges) and an mx3 array V (Vertices). Next you could use `hp=gpatch(E,V,C);`, here C could be 'b' for blue or 'k' for black but you can also spatially vary color by making it a vertex color array. I.e. set it as a mx1 array if you want it to be colormapped or as a mx3 array if it is to represent RGB colors. 
See the demo `DEMO_febio_0009_cube_discrete_springs`, at the end it renders 1000 edges like this: 
![figure3](https://user-images.githubusercontent.com/8392709/50336917-59bd5100-0507-11e9-8c6c-476d2697dafc.gif)

Looking at your simulation perhaps you can group things into: 
1. 1 skeleton handle with the property `'Vertices'` changing in time
2. 1 point set handle where you change `'XData'`,  `'YData'`,  and `'ZData'` in time
3. 1 vector (quiver) handle where you change I think 3 properties. 

So perhaps you only have 7 things to update over time in this way. 

BTW your quiver vectors can also be created using patch graphics see also `HELP_quiverVec` (which provides 3D vectors that are colormapped too and it allows you to change `'Vertices'` too). 

Let me know if this helps.

**Comment by Ipuch** [comment]
Thank you for your quick and complete answer.

Indeed, I had many time steps and many handles. I had 203 time steps at 200Hz which gave 1.01 sec simulations.

Here it is what I've tried to get real time vizualisation:
- I set pause time of the anim8.m cFigure to 0. I didn't succeed to get real-time visualisation.

- I reduced the number of vizualised objects. I only "gpatched" experimental markers in blue and models markers in orange. I didn't succeed to get real-time visualisation.

- I gathered markers (blue ones and orange ones separetely) in the same object, allowing me to do only two gpatch by frames. I didn't succeed to get real-time visualisation.

- I divided the frame rate by 5 and reduced the order of the geosphere from 3 to 1. And it seems like I had faster visualisation.

Here is some extra steps, I've tried.
- I gathered orange and blue markers in the same gpatch. 
- I used two gpatch to generate the skeleton and the muscles.
- I used quiver3Dpatch to create external forces data (measured and predicted). Changing only Vertices in the AnimStruct as you recommended.

At the end, it seems like it is more than two time faster than the previous visualisation for the same frame rate at 200Hz.
![figure3](https://user-images.githubusercontent.com/40755537/50661630-fb32b100-0fa3-11e9-8c80-5d93d5b48911.gif)


---
Subsequent questions: 
- Is there an easy way to verify if my "anim8.m" visualisation is real-time ?
- Is there a systematic to way to export the gif ensuring its frame rate ?
- How can I save a cFigure and an anim8 visualisation to open it later with Matlab?

**Comment by Kevin-Mattheus-Moerman** [comment]
Any luck with this? Let me know how you are getting on.

**Comment by Kevin-Mattheus-Moerman** [comment]
By feature request I meant to open an issue here where you ask for that feature. 

About the markers. Yes I think markers are line/dot data which matlab appears to draw as a certain number of pixels rather than a fixed size, so yeah they change size when you zoom. 

BTW if you not like that the markers have edges drawn you can do `hp.MarkerEdgeColor='none'`(if `hp` is the handle for the patch object). 

Alternatively you could draw the markers using patch data but base them on a Platonic solid (see `HELP_platonic_solid`) so you'll have 4 faces (tetrahedron) up to the 20 face icosahedron. 

I'll close this issue for now but let me know if you need more help.
