### ISSUE TITLE
Real time Step indicator for anim8.

### ISSUE THREAD

**Issue by Ipuch** [gibbonCode/GIBBON#40]
Hi,

Following #36 , I'm asking a feature to get Real time Step indicator for anim8.

Pierre

**Comment by Kevin-Mattheus-Moerman** [comment]
@Ipuch I'll close this issue for now, but let me know if you'd like to reopen. I think this problem is quite challenging since the speed of the graphics handling/updating varies a lot for each application and system. I think the best way to have real time animations would be to export it to a video format with the correct frame rate.
