### ISSUE TITLE
Selecting faces for a fixed boundary 

### ISSUE THREAD

**Issue by BethOK** [gibbonCode/GIBBON#56]
Hi, 
This may seem like a simplistic question, but I'm having issues finding/selecting the faces and nodes in my model. 
I have imported geometry of a tibia and meshed using tetgen, I'd like to fix the bottom of my tibia so that I can apply a simple deformation to my model to perform a mesh convergence test. However I can't find a way to be able to select the bottom faces in my mesh. I tried using the Cb output from my mesh, but it recognises the tibia as one surface.
I was looking at the 'DEMO_febio_0024_active_contraction_tongue' which appears to locate the element bottoms but I don't understand how the element values are derived (i.e. F_element_bottoms=E(:,[1 4 8 5]); %Get element bottom faces). 

Any help would be greatly appreciated. 

Thanks, 
Beth

**Comment by Kevin-Mattheus-Moerman** [comment]
Hi @BethOK. 

Can you specify in more detail what the "bottom of the tibia" means in this case? Do you mean the lower 5 mm of nodes? Is there a cut region such that it ends flat and there is a flat bottom face? 

In `DEMO_febio_0024_active_contraction_tongue` hexahedral elements are used. For that model the bottom faces of the hexahedra are defined as `E(:,[1 4 8 5])`. This approach will not work for your tetrahedral mesh (which is also not structured). 

One way to get a low set of nodes is to get indices using a coordinate "threshold". E.g. if `V` is your vertex/node array then `logicBottom=V(:,3)<(min(V(:,3))+5);` defines a logic for the nodes from the bottom (`min(V(:,3)) defines the lowers Z-coordinate) up to the bottom plus 5. Would this work? The potential downside is that the node set does not end in a regular way (it ends in a "saw-tooth"/jumpy way). However it may do what you want for the point of convergence. You can use `indBottom=find(logicBottom);` to get the linear indices for these nodes. 
If you need indices for faces instead  you can use `logicFacesBottom=any(logicBottom(F),2)`, where the logic is true for faces that have 1 or more nodes which are "low". Alternatively use `logicFacesBottom=all(logicBottom(F),2)` (with `F` the faces) if you only want faces where all of the nodes are "low". 

In some cases I derive node sets from face normals. E.g. if the bottom face points down you can get the face or node normals and check if these points down. To check if they point down (assuming your normals point out of the shape) you can do a dot product with [0 0 -1] (i.e. a unit downward vector). 
E.g. something like this: 
```matlab
sideNormToleranceLevel=1e-6; %Set tolerance level (may depend on mesh quality/units)
n=[0 0 -1]; %Direction for perfect downward face
N=patchNormal(F,V); %Get face normals (unit vectors)
d=abs(dot(N,n(ones(size(N,1),1),:),2)-1); %Dot product -1 (should be zero for bottom)
logicFacesLow=d<sideNormToleranceLevel);
```
However this usually only works with "engineered" surface, since biological surfaces do not have the perfectly flat regions. 

Let me know if this helps.

**Comment by BethOK** [comment]
Hi Kevin, 

Apologies in the delayed response, using the threshold method appears to work well. 

Thank you so much, 

Beth
