### ISSUE TITLE
Volume mesh slicing

### ISSUE THREAD

**Issue by tmedani** [gibbonCode/GIBBON#64]
Hi @Kevin-Mattheus-Moerman 

Regarding our previous discussion, 
https://github.com/gibbonCode/GIBBON/issues/62#issuecomment-625774471

So, it would be nice to have this new feature within Gibbon. 

The idea is almost the same as what you did on surface slicing. 
I'm just using some functions form Gibbon and I have also using an other toolbox (https://github.com/fangq/iso2mesh)

I was able to have some preliminary figure by playing around iso2mesh's functions 

![image](https://user-images.githubusercontent.com/37831900/81617983-4ed4bc00-939b-11ea-8c70-4391b3fd5698.png)

![image](https://user-images.githubusercontent.com/37831900/81618014-5b591480-939b-11ea-8ba9-c77c51cc54ff.png)

The idea later is to add some computed results (scalars or vectors, tensors) in order to see what is going inside the volume. 

Does it make sense for you?

Thanks

Takfarinas

**Comment by Kevin-Mattheus-Moerman** [comment]
Thanks @tmedani for posting this. Can you expand a little on what you want it to do please? Do you want to slice an existing tetrahedral mesh, triangulate it at the planar sliced interface and then adjust/fix the tetrahedral mesh to conform to this sliced interface? 
From this picture it looks like you want to create a slice with a certain thickness and mesh with tetrahedral elements instead. 
Any details you give on how you wish this to work would help.

**Comment by Kevin-Mattheus-Moerman** [comment]
Sorry, I missed your last sentence there. So is this a visualization feature? Like slicing a 3D tetrahedral mesh and to visualize the interior? So we need to slice, triangulate and probably also visualize some node or element data on the slice?

**Comment by Kevin-Mattheus-Moerman** [comment]
FYI This is from `HELP_meshView` but uses simply does not display elements above/below a slice rather than actually cutting.

![sliceTet](https://user-images.githubusercontent.com/8392709/81661559-319ffc00-9434-11ea-9be9-97b2e1e5acfc.gif)

**Comment by Kevin-Mattheus-Moerman** [comment]
This quick and dirty demo below shows the use of `triSurfSlice` on the tetrahedral faces by "pretending the faces describe a surface". It still works but does not close over the cut region. So that would be the next step but should be doable. Can you confirm this is close to what you want? I can also generalize the above `meshView` function to allow for slicing (only showing tets on one side of plane) in any direction. 

```matlab
clear; close all; clc;

%% Creating meshed box
boxDim=[5 6 7]; % Box dimenstions
pointSpacing=0.5; 

[meshStruct]=tetMeshBox(boxDim,pointSpacing);

% Acces output fields
E=meshStruct.elements; %Tetrahedra
V=meshStruct.nodes; %Nodes
Fb=meshStruct.facesBoundary;
%Example olor data on elements (distance to mean for now)
VE=patchCentre(E,V); %Element central coordinates
C=minDist(VE,mean(VE,1)); %Element color data

%Get element faces
[F,CF]=element2patch(E,C); %Element faces and face colors

%% Slice faces "as if surface"
snapTolerance=mean(patchEdgeLengths(F,V))/100; 
n=vecnormalize([0 0 1]); %Normal direction to plane
P=mean(V,1); %Point on plane
[Fc,Vc,Cc,logicSide,Eb]=triSurfSlice(F,V,CF,P,n,snapTolerance);

%%
% Plotting model
cFigure; hold on;
gpatch(Fb,V,'w','none',0.25);
gpatch(Fc(logicSide,:),Vc,Cc(logicSide),'k',1);
axisGeom; 
colorbar;
camlight headlight; 
drawnow; 
```

![sliceTet](https://user-images.githubusercontent.com/8392709/81670728-f1df1180-943f-11ea-815d-ac711517741d.png)

**Comment by tmedani** [comment]
Hi @Kevin-Mattheus-Moerman, 

Thank you for this example, I have reproduced it and it works well. 

However, I don't understand why the triangles are badly well-shaped 

![image](https://user-images.githubusercontent.com/37831900/82250434-50086a80-9900-11ea-8540-a4705c57c6f3.png)

![image](https://user-images.githubusercontent.com/37831900/82250541-80500900-9900-11ea-9a19-172f0f767750.png)


It seems the mesh is modified (flatted) or I missed something. 

However, the `HELP_meshView ` seems to be better and I would try to work on it in order to extract the index of the element on the slice and then assigned the desired value for each element on the slice. 


Best

**Comment by Kevin-Mattheus-Moerman** [comment]
@tmedani yes `triSurfSlice` introduces new nodes and alters triangles (see also `HELP_triSurfSlice` which animates the cutting procedure and you can see the additional nodes introduced where edges cross the cutting plane) . This is needed for a true slice (an actual cut through the mesh edges). 

Perhaps now I understand better what you want. I've just added a function called `meshCleave` (see also `HELP_meshCleave`). Rather than slicing or cutting the mesh it... well I called it cleave, so it cleaves it. By this I mean that it selects elements at, above, or below a plane. You can use it on any mesh type (e.g. patch surface data, but also tetrahedral or hexahedral elements). 
Here is an example of a tetrahedral mesh being "cleaved":
![tetCleave](https://user-images.githubusercontent.com/8392709/82264691-4b25d400-995d-11ea-9cea-73ce0741f51e.png)
This is also shown in `HELP_meshCleave`:
![tetCleaveAnim](https://user-images.githubusercontent.com/8392709/82264778-7c060900-995d-11ea-99a2-041131927782.gif)
The full syntax is `[logicAt,logicAbove,logicBelow]=meshCleave(E,V,P,n,inclusiveSwitch);`. The output `logicAt` is a logic array for the elements "at the plane". If you want linear indices instead (element numbers) then use `indAt=find(logicAt);`. 
You can use the following to get the faces for these elements and their colours so you can visualize them e.g. with `gpatch`: 
```
[F_cleave,CF_cleave]=element2patch(E(logicAt,:),C(logicAt));
```
Can you test run `HELP_meshCleave` and tell me if this is what you want?

**Comment by tmedani** [comment]
Hey @Kevin-Mattheus-Moerman, 

this is awesome, it's this kind of feature that I'm looking for. 

Thanks for the codes and the nice produced figures. 

Sorry if I miss using the word 'slice' instead of the 'cleave' 
but now both function will be useful.

That's great and thanks again.

All the best
